name: flutter_value_bloc
description: Flutter Widgets that make it easy to implement the ValueBloc for list, table and more.
version: 0.5.0-dev.6
repository: https://github.com/BreX900/flutter_value_bloc/tree/master/flutter_value_bloc
issue_tracker: https://github.com/BreX900/flutter_value_bloc/issues
homepage: https://github.com/BreX900/flutter_value_bloc/tree/master/flutter_value_bloc

# flutter pub publish --dry-run

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter

  built_collection: ^4.3.2

  flutter_bloc: ^6.1.1

#  value_bloc: ^0.5.0-dev.6
  value_bloc:
    path: ../value_bloc

  provider: ^4.3.2+3
  pull_to_refresh: ^1.6.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
