name: flutter_value_bloc
description: Flutter Widgets that make it easy to implement the ValueBloc for list, table and more.
version: 1.0.0
repository: https://github.com/BreX900/flutter_value_bloc/tree/master/flutter_value_bloc
issue_tracker: https://github.com/BreX900/flutter_value_bloc/issues
homepage: https://github.com/BreX900/flutter_value_bloc/tree/master/flutter_value_bloc

# flutter pub publish --dry-run

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=1.17.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter

  # wait null safety
  built_collection: ^5.0.0

  flutter_bloc: ^7.0.0

#  value_bloc: ^1.0.0+1
  value_bloc:
    path: ../value_bloc

  provider: ^5.0.0
  pull_to_refresh: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
