name: value_bloc
description: A starting point for Dart libraries or applications.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.12.0 <3.0.0'


dependencies:
  rxdart: ^0.27.2
  pure_extensions: ^3.4.1
  #  pure_extensions:
  #    path: ../../dart_extensions/pure_extensions

  equatable: ^2.0.3
  quiver: ^3.0.1
  collection: ^1.15.0
  built_collection: ^5.1.1

  dartz: ^0.10.0

  bloc: ^7.2.1
  bloc_concurrency: ^0.1.0

dev_dependencies:
  lints: ^1.0.1

  test: ^1.18.2

index_generator:
  filters:
    - black: .*/_.*\.dart$
  indexes:
    - path: lib
      exports:
        - bloc/bloc
        - built_collection/built_collection