name: value_bloc
description: ValueBloc
version: 0.0.1
author: BreX900
homepage: https://github.com/BreX900/flutter_value_bloc

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  meta: ^1.2.3

  equatable: ^1.2.5
  quiver: ^2.1.3

  built_value: ^7.1.0
  built_collection: ^4.3.2

  provider: ^4.3.2+2

  bloc: ^6.0.3

dev_dependencies:
  # flutter packages pub run build_runner build --delete-conflicting-outputs
  # flutter packages pub run build_runner watch --delete-conflicting-outputs
  analyzer: 0.39.17
  build_runner: 1.10.2
  built_value_generator: ^7.1.0

  test: ^1.15.4
  bloc_test: ^7.0.6