name: value_bloc
description: A predictable state management library that helps implement a fetch data from database or another storage
version: 1.1.0
repository: https://github.com/BreX900/flutter_value_bloc/tree/master/value_bloc
issue_tracker: https://github.com/BreX900/flutter_value_bloc/issues
homepage: https://github.com/BreX900/flutter_value_bloc/

# flutter pub publish --dry-run

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  rxdart: ^0.27.0
  pure_extensions: ^3.1.0
#  pure_extensions:
#    path: ../../dart_extensions/pure_extensions

  equatable: ^2.0.2
  quiver: ^3.0.1
  collection: ^1.15.0
  built_value: ^8.0.6
  built_collection: ^5.0.0

  dartz: ^0.10.0-nullsafety.2

  bloc: ^7.0.0

dev_dependencies:
  # flutter packages pub run build_runner build --delete-conflicting-outputs
  # flutter packages pub run build_runner watch --delete-conflicting-outputs
  build_runner:
  built_value_generator: ^8.0.6

  test: