name: value_bloc
description: A predictable state management library that helps implement a fetch data from database or another storage
version: 0.5.1
repository: https://github.com/BreX900/flutter_value_bloc/tree/master/value_bloc
issue_tracker: https://github.com/BreX900/flutter_value_bloc/issues
homepage: https://github.com/BreX900/flutter_value_bloc/

# flutter pub publish --dry-run

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  # wait null safety
  meta: ^1.3.0

#  pure_extensions: ^2.1.0
  pure_extensions:
    path: ../../dart_extensions/pure_extensions
  # wait null safety
  rxdart: ^0.26.0

  equatable: ^2.0.0
  # wait null safety
  quiver: ^3.0.1

  collection: ^1.15.0
  # wait null safety
  built_value: ^8.0.5
  # wait null safety
  built_collection: ^5.0.0

  bloc: ^7.0.0

dev_dependencies:
  # flutter packages pub run build_runner build --delete-conflicting-outputs
  # flutter packages pub run build_runner watch --delete-conflicting-outputs
  analyzer: ^1.5.0
  build_runner: ^1.10.2
  built_value_generator: ^8.0.5

  # wait null safety
  test: ^1.17.2