name: value_bloc
description: A predictable state management library that helps implement a fetch data from database or another storage
version: 1.3.0-dev
repository: https://github.com/BreX900/flutter_value_bloc/tree/master/value_bloc
issue_tracker: https://github.com/BreX900/flutter_value_bloc/issues
homepage: https://github.com/BreX900/flutter_value_bloc/

# dart pub publish --dry-run

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  pure_extensions: ^3.4.0
#  pure_extensions:
#    path: ../../dart_extensions/pure_extensions

  bloc: ^8.0.3

  mek_data_class: ^0.1.0

dev_dependencies:
  # dart run build_runner build --delete-conflicting-outputs
  # dart run build_runner watch --delete-conflicting-outputs
  build_runner: ^2.1.10
  mek_data_class_generator: ^0.1.1

  test: ^1.21.0
  mocktail: ^0.3.0