name: value_bloc
description: A starting point for Dart libraries or applications.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.12.0 <3.0.0'


dependencies:
  meta: ^1.0.0

  rxdart: ^0.27.3

  equatable: ^2.0.3
  collection: ^1.15.0

  bloc: ^8.0.1
  bloc_concurrency: ^0.2.0

dev_dependencies:
  lints: ^1.0.1

  test: ^1.18.2

index_generator:
  exclude:
    - '**.g.dart'
    - '{_,**/_}*.dart'
  indexes:
    - path: lib
      exports:
        - package: bloc/bloc
        - package: built_collection/built_collection